// Extracted from: Spotify 1.2.96.518 (Windows)

syntax = "proto3";

package spotify.playback_platform.context.v1;

import "spotify/playback_platform/context/v1/context_behavior.proto";
import "spotify/playback_platform/context/v1/context_metadata.proto";
import "spotify/playback_platform/context/v1/sequences.proto";
import "spotify/playback_platform/timeline/v1/timeline.proto";
import "spotify/playback_platform/timeline/v1/timeline_behavior.proto";
import "spotify/playback_platform/timeline/v1/timeline_metadata.proto";

option java_multiple_files = true;
option optimize_for = CODE_SIZE;
option java_package = "spotify.playback_platform.context.v1";

message Context {
    ContextBehavior behavior = 1;
    ContextMetadata metadata = 2;
    timeline.v1.TimelineBehavior timeline_behavior = 3;
    timeline.v1.TimelineMetadata timeline_metadata = 4;
    
    oneof structure {
        Sequence sequence = 7;
        PagedSequence paged_sequence = 8;
        ChainSequence chain_sequence = 9;
        timeline.v1.Timeline timeline = 10;
    }
    
    reserved 5 to 6;
    
    reserved "timeline_behavior_override", "timeline_metadata_override";
}
