// Extracted from: Spotify 1.2.96.518 (Windows)

syntax = "proto3";

package spotify.playback_platform.context.v1.behavior;

import "spotify/playback_platform/context/v1/behavior/handler.proto";

option java_multiple_files = true;
option optimize_for = CODE_SIZE;
option java_package = "spotify.playback_platform.context.v1.behavior";

message Events {
    repeated OnMoveOnto on_move_onto = 1;
    message OnMoveOnto {
        Trigger trigger = 1;
        Actions actions = 2;
        bool move_from_play = 7;
        bool move_from_prev = 8;
        bool move_from_next = 9;
        bool skip_from_prev = 10;
        bool skip_from_next = 11;
        bool fail_from_prev = 12;
        bool fail_from_next = 13;
        
        reserved 14 to 31;
    }
    
    repeated OnMoveOnto on_move_onto_child = 2;
    
    repeated OnMovePast on_move_past = 3;
    message OnMovePast {
        Trigger trigger = 1;
        Actions actions = 2;
        bool move_to_next = 8;
        bool move_to_prev = 9;
        bool skip_to_next = 10;
        bool skip_to_prev = 11;
        bool fail_to_next = 12;
        bool fail_to_prev = 13;
        
        reserved 14 to 31;
    }
    
    repeated OnMovePast on_move_past_child = 4;
    
    repeated OnEnterTimespan on_enter_timespan = 5;
    message OnEnterTimespan {
        Trigger trigger = 1;
        Actions actions = 2;
        bool enter_at_beginning_by_playing = 8;
        bool enter_at_beginning_by_seeking = 9;
        bool enter_at_end_by_playing = 10;
        bool enter_at_end_by_seeking = 11;
        
        reserved 12 to 31;
    }
    
    repeated OnLeaveTimespan on_leave_timespan = 6;
    message OnLeaveTimespan {
        Trigger trigger = 1;
        Actions actions = 2;
        bool leave_at_end_by_playing = 8;
        bool leave_at_end_by_seeking = 9;
        bool leave_at_beginning_by_playing = 10;
        bool leave_at_beginning_by_seeking = 11;
        
        reserved 12 to 31;
    }
    
    repeated OnChangePlaying on_change_playing = 7;
    message OnChangePlaying {
        Trigger trigger = 1;
        Actions actions = 2;
        bool position = 8;
        bool duration = 9;
        bool buffered = 10;
        bool playtime = 11;
        bool paused = 12;
        bool resumed = 13;
        bool stalled_buffering_media = 14;
        bool stalled_loading_context = 15;
        
        reserved 16 to 31;
    }
    
    repeated OnChangeSequenceOptions on_change_sequence_options = 8;
    message OnChangeSequenceOptions {
        Trigger trigger = 1;
        Actions actions = 2;
        bool shuffling_sequence = 8;
        bool enhancing_sequence = 9;
        bool repeating_sequence = 10;
        bool repeating_timeline = 11;
        
        reserved 12 to 31;
    }
    
    repeated OnChangeTimelineOptions on_change_timeline_options = 9;
    message OnChangeTimelineOptions {
        Trigger trigger = 1;
        Actions actions = 2;
        bool playback_speed = 8;
        
        reserved 9 to 31;
    }
    
    repeated OnChangeDevice on_change_device = 12;
    message OnChangeDevice {
        Trigger trigger = 1;
        Actions actions = 2;
        
        reserved 8 to 31;
    }
    
    repeated OnChangeLocale on_change_locale = 13;
    message OnChangeLocale {
        Trigger trigger = 1;
        Actions actions = 2;
        bool language_tag = 8;
        bool date_format = 9;
        bool time_format = 10;
        
        reserved 11 to 31;
    }
    
    repeated OnChangeQueue on_change_queue = 14;
    message OnChangeQueue {
        Trigger trigger = 1;
        Actions actions = 2;
        bool sequence_patch = 8;
        
        reserved 9 to 31;
    }
}
