// Extracted from: Spotify 1.2.96.518 (Windows)

syntax = "proto3";

package spotify.playback_platform.context.v1.behavior;

import "spotify/playback_platform/context/v1/sequence_start.proto";

option java_multiple_files = true;
option optimize_for = CODE_SIZE;
option java_package = "spotify.playback_platform.context.v1.behavior";

message Start {
    repeated SequenceStart move_onto_from_prev = 1;
    repeated SequenceStart move_onto_from_next = 2;
    repeated SequenceStart move_onto_from_play = 3;
    repeated SequenceStart skip_onto_from_prev = 4;
    repeated SequenceStart skip_onto_from_next = 5;
    repeated SequenceStart fail_onto_from_prev = 6;
    repeated SequenceStart fail_onto_from_next = 7;
}
