// Extracted from: Spotify 1.2.96.518 (Windows)

syntax = "proto2";

package spotify.event_sender.proto;

option optimize_for = CODE_SIZE;

message AdError {
    optional string request_type = 1;
    optional string error_message = 2;
    optional int64 http_error_code = 3;
    optional string request_url = 4;
    optional string tracking_event = 5;
    optional string error_type = 6;
    optional string ad_id = 7;
    optional string lineitem_id = 8;
    optional string surface = 9;
    optional string ad_content_origin = 10;
    optional string slot = 11;
    optional string request_id = 12;
    repeated string slot_ids = 13;
    optional string type = 14;
    optional string app_startup_id = 15;
    optional string ad_break_id = 16;
}
