// Extracted from: Spotify 1.2.96.518 (Windows)

syntax = "proto2";

package spotify.event_sender.proto;

option optimize_for = CODE_SIZE;

message AudioSessionEvent {
    optional string event = 1;
    optional string context = 2;
    optional string json_data = 3;
    optional bytes playback_id = 4;
    optional string reason = 5;
    optional string feature_identifier = 6;
    optional int32 seek_position = 7;
    optional bool paused = 8;
    optional int64 speed = 9;
    optional int32 fade_start_position = 10;
    optional int32 seek_creator_position = 11;
    optional bool ad_detection_error_on_failure = 12;
    optional int32 ad_detection_fallback_start_position = 13;
}
