// Extracted from: Spotify 1.2.96.518 (Windows)

syntax = "proto2";

package spotify.event_sender.proto;

option optimize_for = CODE_SIZE;

message RawCoreStreamSegment {
    optional bytes playback_id = 1;
    optional int64 start_position = 2;
    optional int64 end_position = 3;
    optional int32 ms_played = 4;
    optional string reason_start = 5;
    optional string reason_end = 6;
    optional double playback_speed = 7;
    optional int64 start_timestamp = 8;
    optional int64 end_timestamp = 9;
    optional bool is_seek = 10;
    optional bool is_pause = 11;
    optional int64 sequence_id = 12;
    optional string media_type = 13;
    optional int64 core_version = 14;
    optional string content_uri = 15;
    optional int64 start_monotonic_timestamp = 16;
    optional int64 end_monotonic_timestamp = 17;
    optional bool is_last = 18;
    optional string provider = 19;
    optional string playback_stack = 20;
    optional string feature_uuid = 21;
    optional bytes stream_id = 22;
    optional string page_instance_id = 23;
    optional string interaction_id = 24;
    optional string play_context = 25;
    optional int64 start_timestamp_internal = 26;
    optional int64 end_timestamp_internal = 27;
    optional int64 sequence_id_internal = 28;
    optional bool is_audio_on = 29;
    optional bool is_video_on = 30;
    optional string video_surface = 31;
    optional bool is_system_seek = 32;
    optional int32 ms_played_accumulated = 33;
    optional int32 ms_played_nominal_accumulated = 34;
    optional string preview_impression_uri = 35;
    optional bool incognito_mode = 36;
    optional string jam_session_id = 37;
    optional bytes clip_playback_id = 38;
    optional string orchestration_stack = 39;
    optional string list_uri = 40;
    optional string output_brand = 41;
    optional string output_model = 42;
    optional string output_category = 43;
    optional string output_connection_type = 44;
    optional int64 ms_played_overlapping_accumulated = 45;
    optional int64 ms_played_nominal_overlapping_accumulated = 46;
    optional int64 ms_narration_overlapping_accumulated = 47;
    optional int64 ms_played_video_accumulated = 48;
    optional int64 ms_played_background_accumulated = 49;
    optional int64 ms_played_fullscreen_accumulated = 50;
    optional int64 ms_played_external_accumulated = 51;
    optional int64 ms_played_post_seek_accumulated = 54;
    map<string, int64> ms_played_video_per_surface_accumulated = 55;
    optional string audio_format = 56;
    optional string streaming_rule = 58;
    optional string referrer = 59;
    optional string source_start = 62;
    optional string source_end = 63;
    optional string player_session_id = 64;
    optional string decision_id = 65;
    optional string play_context_decision_id = 66;
    optional string custom_reporting_attribution = 67;
    optional string agentic_product_type = 68;
    optional string on_demand_type = 69;
    optional bool shuffle = 70;
    optional bool is_repeating_track = 71;
    optional bool is_repeating_context = 72;
    optional int64 playback_start_time = 73;
    optional bool client_offline_at_stream_start = 74;
    repeated string sequence_provider_ids = 75;
    optional bool content_is_downloaded = 76;
    optional bool social_listening = 77;
    optional int64 last_consumption_sequence_id = 78;
    optional string controlling_device_brand = 79;
    optional string controlling_device_model = 80;
    optional string controlling_device_type = 81;
    optional string displayed_content_uri = 82;
    optional string user_intent_uri = 83;
    optional string connect_controller_device_id_v2 = 84;
    optional string local_content_uri = 85;
    optional int64 ms_played_muted_accumulated = 86;
}
