// Extracted from: Spotify 1.2.96.518 (Windows)

syntax = "proto2";

package spotify.event_sender.proto;

option optimize_for = CODE_SIZE;

message TimelineReporterError {
    optional string list_uri = 1;
    optional bytes list_ref = 2;
    optional string list_instance_id = 3;
    optional string item_uri = 4;
    optional string item_uid = 5;
    optional string item_instance_id = 6;
    optional string clip_uid = 7;
    optional bytes playback_rendering_id = 8;
    optional bytes stream_id = 9;
    optional bytes stream_playback_id = 10;
    optional string current_state = 11;
    optional string incoming_event = 12;
    optional string content_uri = 13;
    optional string playback_stack = 14;
    optional int64 core_version = 15;
    optional string client_timestamp = 16;
    optional string error_reason = 17;
}
