// Extracted from: Spotify 1.2.96.518 (Windows)

syntax = "proto2";

package spotify.event_sender.proto;

option optimize_for = CODE_SIZE;

message TracksClusterReport {
    optional int64 num_tracks = 1;
    optional int64 num_dimensions = 2;
    optional int64 num_iterations = 3;
    optional int64 converged = 4;
    optional int64 num_clusters = 5;
    optional int64 total_time = 6;
    optional int64 num_batches = 7;
    optional string tracks = 8;
    optional int64 total_processing_time = 9;
}
