// Extracted from: Spotify 1.2.96.518 (Windows)

syntax = "proto3";

package spotify.list.v1.model.attributes;

option java_multiple_files = true;
option optimize_for = CODE_SIZE;
option java_outer_classname = "GeoblockBlockingTypeProto";
option java_package = "com.spotify.list.v1.model.attributes";

message Geoblock {
    repeated GeoblockBlockingType blocking_types = 1;
}

enum GeoblockBlockingType {
    GEOBLOCK_BLOCKING_TYPE_UNSPECIFIED = 0;
    GEOBLOCK_BLOCKING_TYPE_TITLE = 1;
    GEOBLOCK_BLOCKING_TYPE_DESCRIPTION = 2;
    GEOBLOCK_BLOCKING_TYPE_IMAGE = 3;
}
