// Extracted from: Spotify 1.2.96.518 (Windows)

syntax = "proto3";

package spotify.playback_platform.timeline.v1;

import "spotify/playback_platform/timeline/v1/behavior/reporting.proto";
import "spotify/playback_platform/timeline/v1/behavior/restrictions.proto";
import "spotify/playback_platform/timeline/v1/behavior/seek_into.proto";
import "spotify/playback_platform/timeline/v1/behavior/seek_skip.proto";
import "spotify/playback_platform/timeline/v1/behavior/seek_snap.proto";

option java_multiple_files = true;
option optimize_for = CODE_SIZE;
option java_package = "spotify.playback_platform.timeline.v1";

message TimelineBehavior {
    behavior.Restrictions restrictions = 1;
    behavior.Reporting reporting = 2;
    behavior.SeekSkip seek_to_prev = 3;
    behavior.SeekSkip seek_to_next = 4;
    behavior.SeekSnap seek_snap = 5;
    behavior.SeekInto seek_into = 6;
}
