// Extracted from: Spotify 1.2.96.518 (Windows)

syntax = "proto2";

package spotify.player.proto.state_restore;

option optimize_for = CODE_SIZE;

message KittehBoxRules {
    map<string, bytes> node_aspects = 1;
    
    required Position pos = 2;
    enum Position {
        BETWEEN_TRACKS = 0;
        ON_DELIMITER = 1;
        ON_NODE_TRACK = 2;
    }
    
    required Transition last_transition = 3;
    enum Transition {
        ADVANCE = 0;
        SKIP_NEXT = 1;
        SKIP_PREV = 2;
    }
    
    required int32 context_iteration = 4;
    required bool pending_skip_to = 5;
    optional int64 page_index = 6;
}
