// Extracted from: Spotify 1.2.96.518 (Windows)

syntax = "proto3";

package spotify.ads.proto;

import "google/protobuf/struct.proto";
import "companion_ad.proto";
import "verification_ad.proto";

option optimize_for = CODE_SIZE;

message AdPodResponse {
    map<string, AdlogicAdList> pod = 1;
    int64 next_request = 2;
    string result_details = 3;
    Decision realtime_decision = 5;
    map<string, Decision> slot_realtime_decisions = 6;
    map<string, AdDecisionTree> ad_decision_tree = 8;
    
    reserved 4, 7;
}

message AdDecisionTree {
    repeated string ad_ids = 1;
}

message SlotRealtimeDecisions {
    Decision podcast_preroll = 1;
    Decision podcast_midroll_1 = 2;
    Decision podcast_midroll_2 = 3;
    Decision podcast_midroll_3 = 4;
    Decision podcast_midroll_4 = 5;
    Decision podcast_midroll_5 = 6;
    Decision podcast_postroll = 7;
}

message AdlogicAd {
    string id = 1;
    bool dummy = 2;
    string clickthrough = 3;
    map<string, StringList> tracking_events = 4;
    map<string, string> metadata = 5;
    repeated CoverArt cover_art = 6;
    repeated AudioFile audio = 7;
    repeated VideoFile video = 8;
    repeated DisplayFile display = 9;
    repeated UriFile uri = 10;
    string html = 11;
    bool is_dsa_eligible = 15;
    repeated Companion companions = 16;
    repeated Verification verifications = 17;
    
    oneof cleanupTimeoutMsOptional {
        int32 cleanup_timeout_ms = 12;
    }
    
    oneof sameFrameOptional {
        bool same_frame = 13;
    }
    
    oneof flexResponse {
        google.protobuf.Struct json_payload = 14;
    }
}

message AdlogicAdList {
    repeated AdlogicAd ads = 1;
}

message StringList {
    repeated string list = 1;
}

message TrackingEvents {
    repeated string paused = 1;
    repeated string saved = 2;
    repeated string collapsed = 3;
    repeated string moat = 4;
    repeated string started = 5;
    repeated string clicked = 6;
    repeated string skipped = 7;
    repeated string archived = 8;
    repeated string expanded = 9;
    repeated string first_quartile = 10;
    repeated string rewind = 11;
    repeated string viewed = 12;
    repeated string unmuted = 13;
    repeated string ended = 14;
    repeated string midpoint = 15;
    repeated string resumed = 16;
    repeated string muted = 17;
    repeated string errored = 18;
    repeated string third_quartile = 19;
    repeated string dismissed = 20;
    repeated string viewable_impression = 21;
    repeated string foregrounded = 22;
    repeated string backgrounded = 23;
    repeated string seeked_to = 24;
}

message CoverArt {
    int32 width = 1;
    int32 height = 2;
    string mimetype = 3;
    string media_file = 4;
}

message AudioFile {
    int32 bitrate = 1;
    string mimetype = 2;
    string media_file = 3;
    int32 duration_sec = 4;
}

message VideoFile {
    int32 width = 1;
    int32 height = 2;
    int32 bitrate = 3;
    string mimetype = 4;
    string media_file = 5;
    int32 duration_sec = 6;
}

message DisplayFile {
    int32 width = 1;
    int32 height = 2;
    string mimetype = 3;
    string media_file = 4;
}

message UriFile {
    string id = 1;
    int32 width = 2;
    int32 height = 3;
    string type = 4;
    string media_file = 5;
    int32 duration_sec = 6;
}

message Decision {
    int32 max_ads = 1;
    int32 max_length_seconds = 2;
}
