// Extracted from: Spotify 1.2.96.518 (Windows)

syntax = "proto3";

package spotify.offline.proto;

import "google/protobuf/timestamp.proto";
import "offline.proto";

option optimize_for = CODE_SIZE;

message ListDevicesRequest {
    string user_id = 1;
}

message ListDevicesResponse {
    repeated Device devices = 1;
}

message PutDeviceRequest {
    string user_id = 1;
    
    Body body = 2;
    message Body {
        Device device = 1;
    }
}

message BasicDeviceRequest {
    DeviceKey key = 1;
}

message GetDeviceResponse {
    Device device = 1;
}

message OfflineEnableDeviceRequest {
    DeviceKey key = 1;
    
    Body body = 2;
    message Body {
        bool auto_opc = 1;
    }
    
    string name = 9;
    int32 platform = 7;
    string client_id = 8;
}

message OfflineEnableDeviceResponse {
    Restrictions restrictions = 1;
    
    StatusCode status_code = 2;
    enum StatusCode {
        UNKNOWN = 0;
        OK = 1;
        DEVICE_LIMIT_REACHED = 2;
    }
}

message ListResourcesRequest {
    DeviceKey key = 1;
    string username = 2;
}

message ListResourcesResponse {
    repeated Resource resources = 1;
    google.protobuf.Timestamp server_time = 2;
}

message WriteResourcesRequest {
    DeviceKey key = 1;
    
    Body body = 2;
    message Body {
        repeated ResourceOperation operations = 1;
        string source_device_id = 2;
        string source_cache_id = 3;
    }
    
    string pushMessageIdentifier = 3;
}

message ResourcesUpdate {
    string source_device_id = 1;
    string source_cache_id = 2;
}

message DeltaResourcesRequest {
    DeviceKey key = 1;
    string username = 3;
    
    Body body = 2;
    message Body {
        google.protobuf.Timestamp last_known_server_time = 1;
    }
}

message DeltaResourcesResponse {
    bool delta_update_possible = 1;
    repeated ResourceOperation operations = 2;
    google.protobuf.Timestamp server_time = 3;
}

message GetResourceRequest {
    DeviceKey key = 1;
    string username = 3;
    string uri = 2;
}

message GetResourceResponse {
    Resource resource = 1;
}

message WriteResourcesDetailsRequest {
    DeviceKey key = 1;
    
    Body body = 2;
    message Body {
        repeated Resource resources = 1;
    }
}

message ListDevicesWithResourceRequest {
    string user_id = 1;
    string username = 2;
    
    Body body = 3;
    message Body {
        string uri = 1;
        
        Filters filters = 2;
        message Filters {
            bool include_only_is_supported = 1;
            bool include_only_remote_downloads_enabled = 2;
        }
    }
}

message ListDevicesWithResourceResponse {
    repeated DeviceWithResource deviceWithResource = 1;
    message DeviceWithResource {
        Device device = 1;
        bool is_supported = 2;
        
        oneof _resource {
            Resource resource = 3;
        }
    }
    
    FetchStrategy fetch_strategy = 2;
}

message FetchStrategy {
    oneof fetch_strategy {
        PollStrategy poll_strategy = 1;
        SubStrategy sub_strategy = 2;
    }
}

message PollStrategy {
    int32 interval_ms = 1;
}

message SubStrategy {
    
}

message ClearUserDataRequest {
    string user_id = 1;
}

message ClearDeltaResourcesRequest {
    string user_id = 1;
    string cache_id = 2;
}

message DeleteResourceListRequest {
    string user_id = 1;
    string cache_id = 2;
}

message LicenseStatusRequest {
    string user_id = 1;
}

message LicenseStatusResponse {
    int32 max_licenses = 1;
    int32 free_licenses = 2;
}
