// Extracted from: Spotify 1.2.96.518 (Windows)

syntax = "proto3";

package spotify.collection_cosmos.proto;

import "collection_decoration_policy.proto";
import "collection_item.proto";
import "status.proto";

option objc_class_prefix = "ESP";
option java_multiple_files = true;
option optimize_for = CODE_SIZE;
option java_package = "spotify.collection.esperanto.proto";

message CollectionDecorateRequest {
    repeated string uri = 1;
    string context_uri = 2;
    uint32 update_throttling = 3;
    CollectionArtistDecorationPolicy artist_policy = 4;
    CollectionAlbumDecorationPolicy album_policy = 5;
    CollectionTrackDecorationPolicy track_policy = 6;
    CollectionShowDecorationPolicy show_policy = 7;
    CollectionEpisodeDecorationPolicy episode_policy = 8;
}

message CollectionDecorateResponse {
    Status status = 1;
    repeated CollectionShow show = 2;
    repeated CollectionEpisode episode = 3;
    repeated CollectionAlbum album = 4;
    repeated CollectionArtist artist = 5;
    repeated CollectionTrack track = 6;
}
