// Extracted from: Spotify 1.2.96.518 (Windows)

syntax = "proto3";

package spotify.connectstate;

import "player.proto";
import "devices.proto";
import "media.proto";

option optimize_for = CODE_SIZE;
option java_package = "com.spotify.connectstate.model";

message ClusterUpdate {
    Cluster cluster = 1;
    ClusterUpdateReason update_reason = 2;
    string ack_id = 3;
    repeated string devices_that_changed = 4;
}

message Device {
    DeviceInfo device_info = 1;
    PlayerState player_state = 2;
    PrivateDeviceInfo private_device_info = 3;
    bytes transfer_data = 4;
}

message Cluster {
    int64 changed_timestamp_ms = 1;
    string active_device_id = 2;
    PlayerState player_state = 3;
    map<string, DeviceInfo> device = 4;
    bytes transfer_data = 5;
    uint64 transfer_data_timestamp = 6;
    bool need_full_player_state = 8;
    int64 server_timestamp_ms = 9;
    
    oneof _needs_state_updates {
        bool needs_state_updates = 10;
    }
    
    oneof _started_playing_at_timestamp {
        uint64 started_playing_at_timestamp = 11;
    }
    
    oneof _needs_local_devices {
        bool needs_local_devices = 13;
    }
    
    reserved 7, 12;
}

message PutStateRequest {
    string callback_url = 1;
    Device device = 2;
    MemberType member_type = 3;
    bool is_active = 4;
    PutStateReason put_state_reason = 5;
    uint32 message_id = 6;
    string last_command_sent_by_device_id = 7;
    uint32 last_command_message_id = 8;
    uint64 started_playing_at = 9;
    uint64 has_been_playing_for_ms = 11;
    uint64 client_side_timestamp = 12;
    bool only_write_player_state = 13;
}

message PrivateDeviceInfo {
    string platform = 1;
}

message DeviceInfo {
    bool can_play = 1;
    uint32 volume = 2;
    string name = 3;
    Capabilities capabilities = 4;
    string device_software_version = 6;
    devices.DeviceType device_type = 7;
    string spirc_version = 9;
    string device_id = 10;
    bool is_private_session = 11;
    bool is_social_connect = 12;
    string client_id = 13;
    string brand = 14;
    string model = 15;
    map<string, string> metadata_map = 16;
    string product_id = 17;
    string deduplication_id = 18;
    uint32 selected_alias_id = 19;
    map<uint32, devices.DeviceAlias> device_aliases = 20;
    bool is_offline = 21;
    string public_ip = 22;
    string license = 23;
    bool is_group = 25;
    bool is_dynamic_device = 26;
    repeated string disallow_playback_reasons = 27;
    repeated string disallow_transfer_reasons = 28;
    bool is_locally_discovered = 29;
    bool is_public = 32;
    
    oneof _audio_output_device_info {
        AudioOutputDeviceInfo audio_output_device_info = 24;
    }
    
    oneof _group_instance {
        string group_instance = 31;
    }
    
    oneof _is_wol_capable {
        bool is_wol_capable = 34;
    }
    
    reserved 5, 30;
}

message AudioOutputDeviceInfo {
    oneof _audio_output_device_type {
        AudioOutputDeviceType audio_output_device_type = 1;
    }
    
    oneof _device_name {
        string device_name = 2;
    }
    
    oneof _brand {
        string brand = 3;
    }
    
    oneof _model {
        string model = 4;
    }
    
    oneof _category {
        AudioOutputCategory category = 5;
    }
}

message Capabilities {
    bool can_be_player = 2;
    bool restrict_to_local = 3;
    bool gaia_eq_connect_id = 5;
    bool supports_logout = 6;
    bool is_observable = 7;
    int32 volume_steps = 8;
    repeated string supported_types = 9;
    bool command_acks = 10;
    bool supports_rename = 11;
    bool hidden = 12;
    bool disable_volume = 13;
    bool connect_disabled = 14;
    bool supports_playlist_v2 = 15;
    bool is_controllable = 16;
    bool supports_external_episodes = 17;
    bool supports_set_backend_metadata = 18;
    bool supports_transfer_command = 19;
    bool supports_command_request = 20;
    bool is_voice_enabled = 21;
    bool needs_full_player_state = 22;
    bool supports_gzip_pushes = 23;
    bool supports_set_options_command = 25;
    CapabilitySupportDetails supports_hifi = 26;
    string connect_capabilities = 27;
    bool supports_rooms = 28;
    bool supports_dj = 29;
    common.media.AudioQuality supported_audio_quality = 30;
    bool supports_smart_shuffle_mode = 33;
    bool supports_remote_sleep_timer = 34;
    bool supports_ping_request = 35;
    bool supports_playlist_mixing = 36;
    bool supports_remote_audio_quality_control = 37;
    bool supports_zephyr = 38;
    bool supports_gapless = 39;
    bool supports_crossfade = 40;
    
    reserved 1, 4, 24, 31, 32;
    
    reserved "supported_contexts", "supports_lossless_audio", "supports_playback_speed", "play_token_lost_behavior";
}

message CapabilitySupportDetails {
    bool fully_supported = 1;
    bool user_eligible = 2;
    bool device_supported = 3;
}

message ConnectCommandOptions {
    int32 message_id = 1;
    uint32 target_alias_id = 3;
    
    reserved 4;
}

message ConnectLoggingParams {
    repeated string interaction_ids = 1;
    repeated string page_instance_ids = 2;
}

message LogoutCommand {
    ConnectCommandOptions command_options = 1;
}

message SetVolumeCommand {
    int32 volume = 1;
    ConnectCommandOptions command_options = 2;
    ConnectLoggingParams logging_params = 3;
    string connection_type = 4;
    string sent_by_device_id = 5;
    
    oneof _group_device_identifier {
        string group_device_identifier = 6;
    }
    
    oneof _group_instance {
        string group_instance = 7;
    }
}

message RenameCommand {
    string rename_to = 1;
    ConnectCommandOptions command_options = 2;
}

message ProxyTransferCommand {
    string player_command_json = 1;
    ConnectCommandOptions command_options = 2;
    string target_device_id = 3;
    ConnectLoggingParams logging_params = 4;
    string command_id = 5;
    
    oneof _wol_info {
        WakeOnLanInfo wol_info = 6;
    }
}

message ProxyWakeCommand {
    string target_device_id = 1;
    WakeOnLanInfo wol_info = 2;
    ConnectLoggingParams logging_params = 3;
    string command_id = 4;
}

message SetBackendMetadataCommand {
    map<string, string> metadata = 1;
}

message LocalDevice {
    string device_id = 1;
    string device_name = 2;
    devices.DeviceType device_type = 3;
    string client_id = 4;
    string product_id = 5;
    string brand = 6;
    string model = 7;
    string local_ip = 8;
    repeated string supported_media_types = 11;
    bool supports_dj = 12;
    bool supports_on_demand = 13;
    bool is_voice_enabled = 14;
    string license = 15;
    CapabilitySupportDetails supports_hifi = 16;
    repeated string disallow_reasons = 17;
    bool supports_external_episodes = 19;
    
    oneof _alias_id {
        uint32 alias_id = 9;
    }
    
    oneof _connect_capabilities {
        string connect_capabilities = 18;
    }
    
    oneof _wol_info {
        WakeOnLanInfo wol_info = 20;
    }
}

message WakeOnLanInfo {
    bytes mac_address = 1;
    uint32 port = 2;
    uint32 retries = 3;
    uint32 delay_ms = 4;
    bool broadcast_on_all_interfaces = 5;
}

message AddDeviceToGroupCommand {
    string group_device_identifier = 1;
    ConnectCommandOptions command_options = 2;
    ConnectLoggingParams logging_params = 3;
    string group_instance = 4;
}

message AddDeviceToGroupCommandResponse {
    bool success = 1;
    
    oneof _error {
        Error error = 2;
    }
    
    enum Error {
        UNKNOWN_ERROR = 0;
        TIMEOUT = 1;
        DEVICE_NOT_GROUPABLE = 3;
        MAX_NUMBER_OF_DEVICES_REACHED = 4;
        NOT_IMPLEMENTED = 6;
        NOT_SUPPORTED = 7;
        INTEGRATION_ERROR = 8;
        SDK_ERROR = 9;
        CONNECT_ERROR = 10;
        GROUP_NOT_FOUND = 11;
        INVALID_GROUP = 12;
    }
}

message RemoveDeviceFromGroupCommand {
    string group_device_identifier = 1;
    ConnectCommandOptions command_options = 2;
    ConnectLoggingParams logging_params = 3;
    string group_instance = 4;
}

message RemoveDeviceFromGroupCommandResponse {
    bool success = 1;
    
    oneof _error {
        Error error = 2;
    }
    
    enum Error {
        UNKNOWN_ERROR = 0;
        TIMEOUT = 1;
        DEVICE_NOT_REMOVABLE = 3;
        NOT_IMPLEMENTED = 5;
        NOT_SUPPORTED = 6;
        INTEGRATION_ERROR = 7;
        SDK_ERROR = 8;
        CONNECT_ERROR = 9;
        GROUP_NOT_FOUND = 10;
        INVALID_GROUP = 11;
    }
}

message DeleteGroupCommand {
    ConnectCommandOptions command_options = 1;
    ConnectLoggingParams logging_params = 2;
    string group_instance = 3;
}

message DeleteGroupCommandResponse {
    bool success = 1;
    
    oneof _error {
        Error error = 2;
    }
    
    enum Error {
        UNKNOWN_ERROR = 0;
        TIMEOUT = 1;
        NOT_IMPLEMENTED = 4;
        NOT_SUPPORTED = 5;
        INTEGRATION_ERROR = 6;
        SDK_ERROR = 7;
        CONNECT_ERROR = 8;
        GROUP_NOT_FOUND = 9;
        INVALID_GROUP = 10;
    }
}

message ResyncGroupDataCommand {
    
}

message ResyncGroupDataCommandResponse {
    bool success = 1;
    
    oneof _error {
        Error error = 2;
    }
    
    enum Error {
        UNKNOWN_ERROR = 0;
        TIMEOUT = 1;
        NOT_IMPLEMENTED = 2;
        SDK_ERROR = 3;
        CONNECT_ERROR = 4;
    }
}

enum AudioOutputDeviceType {
    UNKNOWN_AUDIO_OUTPUT_DEVICE_TYPE = 0;
    BUILT_IN_SPEAKER = 1;
    LINE_OUT = 2;
    BLUETOOTH = 3;
    AIRPLAY = 4;
    AUTOMOTIVE = 5 [deprecated = true];
    CAR_PROJECTED = 6;
}

enum AudioOutputCategory {
    AUDIO_OUTPUT_CATEGORY_UNKNOWN = 0;
    AUDIO_OUTPUT_CATEGORY_CAR = 1;
    AUDIO_OUTPUT_CATEGORY_HEADPHONES = 2;
    AUDIO_OUTPUT_CATEGORY_SPEAKER = 3;
    AUDIO_OUTPUT_CATEGORY_WEARABLE = 4;
    AUDIO_OUTPUT_CATEGORY_GLASSES = 5;
    AUDIO_OUTPUT_CATEGORY_APP = 6;
}

enum PutStateReason {
    UNKNOWN_PUT_STATE_REASON = 0;
    SPIRC_HELLO = 1;
    SPIRC_NOTIFY = 2;
    NEW_DEVICE = 3;
    PLAYER_STATE_CHANGED = 4;
    VOLUME_CHANGED = 5;
    PICKER_OPENED = 6;
    BECAME_INACTIVE = 7;
    ALIAS_CHANGED = 8;
    NEW_CONNECTION = 9;
    PULL_PLAYBACK = 10;
    AUDIO_DRIVER_INFO_CHANGED = 11;
    PUT_STATE_RATE_LIMITED = 12;
    BACKEND_METADATA_APPLIED = 13;
    LOCAL_DEVICES_CHANGED = 14;
    GROUP_STATE_CHANGED = 15;
    PRIVATE_SESSION_CHANGED = 16;
}

enum MemberType {
    SPIRC_V2 = 0;
    SPIRC_V3 = 1;
    CONNECT_STATE = 2;
    CONNECT_STATE_EXTENDED = 5;
    ACTIVE_DEVICE_TRACKER = 6;
    PLAY_TOKEN = 7;
}

enum ClusterUpdateReason {
    UNKNOWN_CLUSTER_UPDATE_REASON = 0;
    DEVICES_DISAPPEARED = 1;
    DEVICE_STATE_CHANGED = 2;
    NEW_DEVICE_APPEARED = 3;
    DEVICE_VOLUME_CHANGED = 4;
    DEVICE_ALIAS_CHANGED = 5;
    DEVICE_NEW_CONNECTION = 6;
}
