// Extracted from: Spotify 1.2.96.518 (Windows)

syntax = "proto3";

package spotify.debug_tracer.proto;

option objc_class_prefix = "ESP";
option java_multiple_files = true;
option optimize_for = CODE_SIZE;
option java_package = "com.spotify.stream_reporting_debug_tracer_esperanto.proto";

service DebugTracerService {
    rpc trace(DebugTracerRequest) returns (DebugTracerResponse);
    rpc trace_playback_id(DebugTracerPlaybackIdRequest) returns (DebugTracerResponse);
    rpc trace_stream_handle(DebugTracerStreamHandleRequest) returns (DebugTracerResponse);
}

message DebugTracerRequest {
    DebugTracePoint debug_trace_point = 1;
    bytes playback_id = 2;
    uint32 raw_stream_handle = 3;
}

message DebugTracerPlaybackIdRequest {
    DebugTracePoint debug_trace_point = 1;
    bytes playback_id = 2;
}

message DebugTracerStreamHandleRequest {
    DebugTracePoint debug_trace_point = 1;
    uint32 raw_stream_handle = 2;
}

message DebugTracerResponse {
    
}

enum DebugTracePoint {
    DEBUG_TRACE_POINT_SESSION_IMPL_START_OR_RESUME_START = 0;
    DEBUG_TRACE_POINT_SESSION_IMPL_START_OR_RESUME_BEFORE_SEEK = 1;
    DEBUG_TRACE_POINT_SESSION_IMPL_START_OR_RESUME_CREATE_HANDLE = 2;
    DEBUG_TRACE_POINT_SESSION_IMPL_START_OR_RESUME_FAIL_ONCE = 3;
    DEBUG_TRACE_POINT_SESSION_IMPL_START_OR_RESUME_FAIL_MULTIPLE_TIMES = 4;
    DEBUG_TRACE_POINT_SESSION_IMPL_DESTRUCTOR = 5;
    DEBUG_TRACE_POINT_SESSION_IMPL_END = 6;
    DEBUG_TRACE_POINT_STREAM_REPORTING_START = 7;
    DEBUG_TRACE_POINT_STREAM_REPORTING_START_ADD_EVENT_FAILED = 8;
    DEBUG_TRACE_POINT_STREAM_REPORTING_START_END = 9;
    DEBUG_TRACE_POINT_STREAM_REPORTING_PROGRESS_HANDLE_MISMATCH_BUT_VALID = 10;
    DEBUG_TRACE_POINT_STREAM_REPORTING_PROGRESS_REPLACE_EVENT_FAILED = 11;
    DEBUG_TRACE_POINT_STREAM_REPORTING_SEEK_HANDLE_MISMATCH_BUT_VALID = 12;
    DEBUG_TRACE_POINT_STREAM_REPORTING_SEEK_REPLACE_EVENT_FAILED = 13;
    DEBUG_TRACE_POINT_STREAM_REPORTING_END_HANDLE_MISMATCH_BUT_VALID = 14;
    DEBUG_TRACE_POINT_STREAM_REPORTING_END_START = 15;
    DEBUG_TRACE_POINT_STREAM_REPORTING_END_REPLACE_EVENT_FAILED = 16;
    DEBUG_TRACE_POINT_STREAM_REPORTING_END_BEGIN_COMMIT_EVENT = 17;
    DEBUG_TRACE_POINT_STREAM_REPORTING_END_COMMIT_EVENT_FAILED = 18;
    DEBUG_TRACE_POINT_STREAM_REPORTING_END_END = 19;
    DEBUG_TRACE_POINT_SESSION_IMPL_START_OR_RESUME_RESUMED = 20;
    DEBUG_TRACE_POINT_SESSION_IMPL_SUSPEND = 21;
    DEBUG_TRACE_POINT_SESSION_TRACK_PLAYER_IMPL_PREPARE_AND_RUN_PENDING_OPEN_AND_PLAY = 22;
    DEBUG_TRACE_POINT_SESSION_TRACK_PLAYER_IMPL_OPEN_TRACK_START = 23;
    DEBUG_TRACE_POINT_SESSION_TRACK_PLAYER_IMPL_OPEN_TRACK_END_SONG_RESUME = 24;
    DEBUG_TRACE_POINT_SESSION_TRACK_PLAYER_IMPL_PLAY = 25;
    DEBUG_TRACE_POINT_SESSION_TRACK_PLAYER_IMPL_PAUSE = 26;
    DEBUG_TRACE_POINT_SESSION_TRACK_PLAYER_IMPL_CLOSE_TRACK_START = 27;
    DEBUG_TRACE_POINT_SESSION_TRACK_PLAYER_IMPL_CLOSE_TRACK_END = 28;
    DEBUG_TRACE_POINT_SESSION_TRACK_PLAYER_IMPL_CLOSE_TRACK_ALREADY_CLOSED = 29;
    DEBUG_TRACE_POINT_SESSION_TRACK_PLAYER_IMPL_CLOSE_TRACK_HAS_END_SONG_SESSION = 30;
    DEBUG_TRACE_POINT_SESSION_TRACK_PLAYER_IMPL_CLOSE_TRACK_SUSPEND_END_SONG = 31;
    DEBUG_TRACE_POINT_SESSION_TRACK_PLAYER_IMPL_CLOSE_TRACK_HAS_STREAM_REPORTING_SESSION = 32;
    DEBUG_TRACE_POINT_SESSION_TRACK_PLAYER_IMPL_PROCESS_END_AD_AT_CLOSE = 33;
    DEBUG_TRACE_POINT_SESSION_TRACK_PLAYER_IMPL_PROCESS_END_SONG_AT_CLOSE = 34;
    DEBUG_TRACE_POINT_SESSION_TRACK_PLAYER_IMPL_CTOR_START = 35;
    DEBUG_TRACE_POINT_SESSION_TRACK_PLAYER_IMPL_CTOR_NOT_LOCAL_NOT_AUDIO = 36;
    DEBUG_TRACE_POINT_SESSION_TRACK_PLAYER_IMPL_CTOR_END = 37;
    DEBUG_TRACE_POINT_SESSION_TRACK_PLAYER_IMPL_SEND_NOT_PLAYED_HAS_ES = 38;
    DEBUG_TRACE_POINT_SESSION_TRACK_PLAYER_IMPL_SEND_NOT_PLAYED_NO_ES = 39;
    DEBUG_TRACE_POINT_PENDING_EVENTS_IMPL_ADD_EVENT_START = 40;
    DEBUG_TRACE_POINT_PENDING_EVENTS_IMPL_ADD_EVENT_FAILED_OPENING_DB = 41;
    DEBUG_TRACE_POINT_PENDING_EVENTS_IMPL_ADD_EVENT_NO_OWNER_PROVIDED = 42;
    DEBUG_TRACE_POINT_PENDING_EVENTS_IMPL_ADD_EVENT_SERIALIZATION_ERROR = 43;
    DEBUG_TRACE_POINT_PENDING_EVENTS_IMPL_ADD_EVENT_FAILED_ALLOCATING_SEQUENCE_NUMBER = 44;
    DEBUG_TRACE_POINT_PENDING_EVENTS_IMPL_ADD_EVENT_FAILED_ADDING_EVENT_TO_DB = 45;
    DEBUG_TRACE_POINT_PENDING_EVENTS_IMPL_ADD_EVENT_FAILED_WRITING_TO_DB = 46;
    DEBUG_TRACE_POINT_PENDING_EVENTS_IMPL_ADD_EVENT_END = 47;
    DEBUG_TRACE_POINT_PENDING_EVENTS_IMPL_REPLACE_EVENT_BAD_INPUT_PENDING_EVENTS_TOKEN = 48;
    DEBUG_TRACE_POINT_PENDING_EVENTS_IMPL_REPLACE_EVENT_FAILED_OPENING_DB = 49;
    DEBUG_TRACE_POINT_PENDING_EVENTS_IMPL_REPLACE_EVENT_FAILED_GETTING_EVENT_FROM_DB = 50;
    DEBUG_TRACE_POINT_PENDING_EVENTS_IMPL_REPLACE_EVENT_SERIALIZATION_ERROR = 51;
    DEBUG_TRACE_POINT_PENDING_EVENTS_IMPL_REPLACE_EVENT_FAILED_OVERWRITING_IN_DB = 52;
    DEBUG_TRACE_POINT_PENDING_EVENTS_IMPL_REPLACE_EVENT_FAILED_WRITING_TO_DB = 53;
    DEBUG_TRACE_POINT_PENDING_EVENTS_IMPL_COMMIT_EVENT_START = 54;
    DEBUG_TRACE_POINT_PENDING_EVENTS_IMPL_COMMIT_EVENT_BAD_INPUT_PENDING_EVENTS_TOKEN = 55;
    DEBUG_TRACE_POINT_PENDING_EVENTS_IMPL_COMMIT_EVENT_FAILED_OPENING_DB = 56;
    DEBUG_TRACE_POINT_PENDING_EVENTS_IMPL_COMMIT_EVENT_DECRYPTION_ERROR = 57;
    DEBUG_TRACE_POINT_PENDING_EVENTS_IMPL_COMMIT_EVENT_EVENT_SENDER_ERROR = 58;
    DEBUG_TRACE_POINT_PENDING_EVENTS_IMPL_COMMIT_EVENT_FAILED_REMOVING_EVENT_FROM_DB = 59;
    DEBUG_TRACE_POINT_PENDING_EVENTS_IMPL_COMMIT_EVENT_END = 60;
    DEBUG_TRACE_POINT_BETAMAX_STREAM_REPORTING_START = 61;
    DEBUG_TRACE_POINT_BETAMAX_STREAM_REPORTING_START_ERROR = 62;
    DEBUG_TRACE_POINT_BETAMAX_STREAM_REPORTING_START_END = 63;
    DEBUG_TRACE_POINT_BETAMAX_STREAM_REPORTING_PROGRESS = 64;
    DEBUG_TRACE_POINT_BETAMAX_STREAM_REPORTING_PROGRESS_ERROR = 65;
    DEBUG_TRACE_POINT_BETAMAX_STREAM_REPORTING_PROGRESS_END = 66;
    DEBUG_TRACE_POINT_BETAMAX_STREAM_REPORTING_SEEK = 67;
    DEBUG_TRACE_POINT_BETAMAX_STREAM_REPORTING_SEEK_ERROR = 68;
    DEBUG_TRACE_POINT_BETAMAX_STREAM_REPORTING_SEEK_END = 69;
    DEBUG_TRACE_POINT_BETAMAX_STREAM_REPORTING_END = 70;
    DEBUG_TRACE_POINT_BETAMAX_STREAM_REPORTING_END_ERROR = 71;
    DEBUG_TRACE_POINT_BETAMAX_STREAM_REPORTING_END_END = 72;
    DEBUG_TRACE_POINT_END_VIDEO_CREATE = 73;
    DEBUG_TRACE_POINT_END_VIDEO_CREATE_ERROR = 74;
    DEBUG_TRACE_POINT_END_VIDEO_CREATE_END = 75;
    DEBUG_TRACE_POINT_END_VIDEO_UPDATE = 76;
    DEBUG_TRACE_POINT_END_VIDEO_UPDATE_ERROR = 77;
    DEBUG_TRACE_POINT_END_VIDEO_UPDATE_END = 78;
    DEBUG_TRACE_POINT_END_VIDEO_SEND = 79;
    DEBUG_TRACE_POINT_END_VIDEO_SEND_ERROR = 80;
    DEBUG_TRACE_POINT_END_VIDEO_SEND_END = 81;
    DEBUG_TRACE_POINT_BETAMAX_STREAM_REPORTING_ON_PLAYBACK_CREATED = 82;
    DEBUG_TRACE_POINT_BETAMAX_STREAM_REPORTING_ON_READY = 83;
    DEBUG_TRACE_POINT_END_VIDEO_ON_PLAYBACK_CREATED = 84;
    DEBUG_TRACE_POINT_END_VIDEO_ON_READY = 85;
    DEBUG_TRACE_POINT_UNKNOWN = 86;
}
