// Extracted from: Spotify 1.2.96.518 (Windows)

syntax = "proto3";

package spotify.desktop.issue_reporter_esperanto.proto;

option optimize_for = CODE_SIZE;

service DesktopIssueReporter {
    rpc SubmitIssue(SubmitIssueRequest) returns (SubmitIssueResponse);
}

message FileAttachment {
    string name = 1;
    string base64 = 2;
}

message SubmitIssueRequest {
    string summary = 1;
    string description = 2;
    string project_key = 3;
    string feature = 4;
    repeated string labels = 5;
    repeated FileAttachment files = 6;
}

message SubmitIssueResponse {
    string ticket_key = 1;
    bool success = 3;
    
    oneof _error {
        string error = 2;
    }
}
