// Extracted from: Spotify 1.2.96.518 (Windows)

syntax = "proto3";

package spotify.desktop.commands_esperanto.proto;

option optimize_for = CODE_SIZE;

service DesktopCommands {
    rpc SubscribeCommand(SubscribeCommandRequest) returns (stream SubscribeCommandResponse);
}

message SubscribeCommandRequest {
    DesktopCommand type = 1;
}

message SubscribeCommandResponse {
    DesktopCommand type = 1;
}

enum DesktopCommand {
    DESKTOP_COMMAND_UNSPECIFIED = 0;
    DESKTOP_COMMAND_LOGOUT = 1;
    DESKTOP_COMMAND_BROWSE_BACKWARD = 2;
    DESKTOP_COMMAND_BROWSE_FORWARD = 3;
    DESKTOP_COMMAND_CREATE_NEW_FOLDER = 4;
    DESKTOP_COMMAND_CREATE_NEW_PLAYLIST = 5;
    DESKTOP_COMMAND_ENTER_FULLSCREEN = 6;
    DESKTOP_COMMAND_LEAVE_FULLSCREEN = 7;
    DESKTOP_COMMAND_SET_SCROLLER_STYLE_ALWAYS_VISIBLE = 8;
    DESKTOP_COMMAND_SET_SCROLLER_STYLE_OVERLAY = 9;
    DESKTOP_COMMAND_ENTER_CINEMA_MODE = 10;
    DESKTOP_COMMAND_LEAVE_CINEMA_MODE = 11;
    DESKTOP_COMMAND_CUT = 100;
    DESKTOP_COMMAND_COPY = 101;
    DESKTOP_COMMAND_COPY_ADVANCED = 102;
    DESKTOP_COMMAND_PASTE = 103;
    DESKTOP_COMMAND_DELETE = 104;
    DESKTOP_COMMAND_SELECT_ALL = 105;
    DESKTOP_COMMAND_SELECT_NONE = 106;
    DESKTOP_COMMAND_FILTER = 107;
    DESKTOP_COMMAND_SHOW_ABOUT = 200;
    DESKTOP_COMMAND_SHOW_ACCOUNT = 201;
    DESKTOP_COMMAND_SHOW_COMMUNITY = 202;
    DESKTOP_COMMAND_SHOW_HELP = 203;
    DESKTOP_COMMAND_SHOW_LICENSES = 204;
    DESKTOP_COMMAND_SHOW_LICENSING_INFORMATION = 205;
    DESKTOP_COMMAND_SHOW_SCTA_INFORMATION = 206;
    DESKTOP_COMMAND_SHOW_PREFERENCES = 207;
    DESKTOP_COMMAND_SHOW_SEARCH = 208;
    DESKTOP_COMMAND_SHOW_DEBUG_WINDOW = 209;
    DESKTOP_COMMAND_SHOW_REPORT_ISSUE = 210;
    DESKTOP_COMMAND_SHOW_MINI_PLAYER = 211;
    DESKTOP_COMMAND_HIDE_MINI_PLAYER = 212;
    DESKTOP_COMMAND_SET_PLATFORM_EMULATION_AUTO = 300;
    DESKTOP_COMMAND_SET_PLATFORM_EMULATION_MACOS = 301;
    DESKTOP_COMMAND_SET_PLATFORM_EMULATION_WINDOWS = 302;
    DESKTOP_COMMAND_SET_PLATFORM_EMULATION_LINUX = 303;
    DESKTOP_COMMAND_SET_RTL_EMULATION_AUTO = 304;
    DESKTOP_COMMAND_SET_RTL_EMULATION_ON = 305;
    DESKTOP_COMMAND_SET_RTL_EMULATION_OFF = 306;
}
