// Extracted from: Spotify 1.2.96.518 (Windows)

syntax = "proto3";

package spotify.desktop.zoom_esperanto.proto;

option optimize_for = CODE_SIZE;

service DesktopZoom {
    rpc GetZoomLevel(GetZoomLevelRequest) returns (GetZoomLevelResponse);
    rpc SetZoomLevel(SetZoomLevelRequest) returns (SetZoomLevelResponse);
    rpc ZoomIn(ZoomInRequest) returns (ZoomInResponse);
    rpc ZoomOut(ZoomOutRequest) returns (ZoomOutResponse);
}

message GetZoomLevelRequest {
    
}

message SetZoomLevelRequest {
    double zoomLevel = 1;
}

message GetZoomLevelResponse {
    double zoomLevel = 1;
}

message SetZoomLevelResponse {
    
}

message ZoomInRequest {
    
}

message ZoomInResponse {
    
}

message ZoomOutRequest {
    
}

message ZoomOutResponse {
    
}
