// Extracted from: Spotify 1.2.96.518 (Windows)

syntax = "proto3";

package spotify.local_files_esperanto.proto;

import "google/protobuf/empty.proto";
import "policy/playlist_track_decoration_policy.proto";
import "playlist_track_state.proto";
import "metadata/track_metadata.proto";

option objc_class_prefix = "ESP";
option optimize_for = CODE_SIZE;
option java_package = "com.spotify.local_files_esperanto.proto";

service LocalFiles {
    rpc GetTracks(GetTracksRequest) returns (GetTracksResponse);
    rpc SubscribeTracks(GetTracksRequest) returns (stream GetTracksResponse);
    rpc GetScannerStatus(google.protobuf.Empty) returns (GetScannerStatusResponse);
    rpc SubscribeScannerStatus(google.protobuf.Empty) returns (stream GetScannerStatusResponse);
    rpc GetSources(google.protobuf.Empty) returns (GetSourcesResponse);
    rpc SubscribeSources(google.protobuf.Empty) returns (stream GetSourcesResponse);
    rpc MutateDefaultSource(DefaultSource) returns (MutateSourceResponse);
    rpc MutateDefaultSources(MutateDefaultSourcesRequest) returns (MutateSourcesResponse);
    rpc AddFolder(Folder) returns (MutateSourceResponse);
    rpc RemoveFolder(Folder) returns (MutateSourceResponse);
    rpc NotifyDefaultSources(google.protobuf.Empty) returns (google.protobuf.Empty);
}

message Item {
    oneof _add_time {
        uint32 add_time = 1;
    }
    
    oneof _metadata {
        cosmos_util.proto.TrackMetadata metadata = 2;
    }
    
    oneof _collection_state {
        playlist.cosmos.proto.TrackCollectionState collection_state = 3;
    }
    
    oneof _row_id {
        string row_id = 4;
    }
    
    oneof _content_uri {
        string content_uri = 5;
    }
}

message Response {
    repeated Item item = 1;
    
    oneof _unfiltered_length {
        uint32 unfiltered_length = 2;
    }
}

message ResponseStatus {
    int32 status_code = 1;
    string reason = 2;
}

message Range {
    int32 start = 1;
    int32 length = 2;
}

message Query {
    string text_filter = 1;
    
    SortBy sort_by = 2;
    enum SortBy {
        NO_SORT = 0;
        ALBUM_ARTIST_NAME_ASC = 1;
        ALBUM_ARTIST_NAME_DESC = 2;
        TRACK_NUMBER_ASC = 3;
        TRACK_NUMBER_DESC = 4;
        DISC_NUMBER_ASC = 5;
        DISC_NUMBER_DESC = 6;
        ALBUM_NAME_ASC = 7;
        ALBUM_NAME_DESC = 8;
        ARTIST_NAME_ASC = 9;
        ARTIST_NAME_DESC = 10;
        NAME_ASC = 11;
        NAME_DESC = 12;
        ADD_TIME_ASC = 13;
        ADD_TIME_DESC = 14;
        LENGTH_ASC = 15;
        LENGTH_DESC = 16;
    }
    
    Range range = 3;
    uint32 min_length = 4;
    bool remove_duplicate_links = 5;
}

message GetTracksRequest {
    Query query = 1;
    playlist.cosmos.proto.PlaylistTrackDecorationPolicy policy = 2;
}

message GetTracksResponse {
    ResponseStatus status = 1;
    Response data = 2;
}

message GetScannerStatusResponse {
    ScannerStatus scanner_status = 1;
    enum ScannerStatus {
        UNKNOWN = 0;
        IDLE = 1;
        IN_PROGRESS = 2;
    }
}

message DefaultSource {
    Id id = 1;
    enum Id {
        UNKNOWN = 0;
        ITUNES = 1;
        DOWNLOADS = 2;
        MY_MUSIC = 3;
        WINDOWS_MUSIC_LIBRARY = 4;
        ANDROID_MEDIA_STORE = 5;
        IOS_DOCUMENTS = 6;
    }
    
    bool enabled = 2;
}

message Folder {
    string path = 1;
}

message GetSourcesResponse {
    repeated DefaultSource default_sources = 1;
    repeated Folder folders = 2;
}

message MutateSourceResponse {
    Result result = 1;
    enum Result {
        UNKNOWN = 0;
        SUCCESS = 1;
        NOT_FOUND = 2;
        NOT_CHANGED = 3;
    }
}

message MutateDefaultSourcesRequest {
    repeated DefaultSource sources = 1;
}

message MutateSourcesResponse {
    repeated MutateSourceResponse sources = 1;
}
