// Extracted from: Spotify 1.2.96.518 (Windows)

syntax = "proto3";

package spotify.offline.proto.v2;

import "google/protobuf/any.proto";
import "google/protobuf/empty.proto";
import "extension_kind.proto";

option optimize_for = CODE_SIZE;
option java_package = "com.spotify.offline.offlineplugin_proto";

service OfflinePlugin {
    rpc identify(IdentifyCommand) returns (IdentifyResponse);
    rpc download(DownloadCommand) returns (stream DownloadResponse);
    rpc stopDownload(StopDownloadCommand) returns (google.protobuf.Empty);
    rpc remove(RemoveCommand) returns (google.protobuf.Empty);
}

message TargetFormat {
    int32 bitrate = 1;
}

message Metadata {
    Header header = 1;
    message Header {
        int32 status_code = 1;
        bool is_empty = 2;
    }
    
    google.protobuf.Any extension_data = 2;
}

message IdentifyCommand {
    Header header = 1;
    message Header {
        TargetFormat target_format = 1;
    }
    
    repeated Query query = 2;
    message Query {
        string link = 1;
        map<int32, Metadata> metadata = 2;
    }
}

message IdentifyResponse {
    map<string, Result> results = 1;
    
    message Result {
        Status status = 1;
        enum Status {
            UNKNOWN = 0;
            MISSING = 1;
            COMPLETE = 2;
            NOT_APPLICABLE = 3;
        }
        
        int64 estimated_file_size = 2;
    }
}

message DownloadCommand {
    string link = 1;
    TargetFormat target_format = 2;
    map<int32, Metadata> metadata = 3;
}

message DownloadResponse {
    string link = 1;
    bool complete = 2;
    int64 file_size = 3;
    int64 bytes_downloaded = 4;
    
    Error error = 5;
    enum Error {
        OK = 0;
        TEMPORARY_ERROR = 1;
        PERMANENT_ERROR = 2;
        DISK_FULL = 3;
    }
    
    string error_details = 6;
}

message StopDownloadCommand {
    string link = 1;
}

message RemoveCommand {
    Header header = 1;
    message Header {
        
    }
    
    repeated Query query = 2;
    message Query {
        string link = 1;
        map<int32, Metadata> metadata = 2;
    }
}

message PluginMetadata {
    string name = 1;
    repeated LinkType supported_link_types = 2;
    ResourceType resource_type = 3;
    repeated extendedmetadata.ExtensionKind extension_kinds = 4;
    bool best_effort = 5;
}

enum LinkType {
    EMPTY = 0;
    TRACK = 1;
    EPISODE = 2;
}

enum ResourceType {
    OTHER = 0;
    AUDIO = 1;
    DRM = 2;
    IMAGE = 3;
    VIDEO = 4;
}
