// Extracted from: Spotify 1.2.96.518 (Windows)

syntax = "proto3";

package spotify.remote_config.esperanto.proto;

import "esperanto_options.proto";

option objc_class_prefix = "ESP";
option optimize_for = CODE_SIZE;
option java_package = "com.spotify.remoteconfig.esperanto.proto";

service RemoteConfig {
    rpc lookupBool(LookupRequest) returns (BoolResponse);
    rpc lookupInt(LookupRequest) returns (IntResponse);
    rpc lookupEnum(LookupRequest) returns (EnumResponse);
}

message LookupRequest {
    string scope = 1;
    string name = 2;
}

message BoolResponse {
    oneof _value {
        bool value = 1;
    }
}

message IntResponse {
    oneof _value {
        int32 value = 1;
    }
}

message EnumResponse {
    oneof _value {
        string value = 1;
    }
}
