// Extracted from: Spotify 1.2.96.518 (Windows)

syntax = "proto3";

package spotify.exclusive_mode_esperanto.proto;

option objc_class_prefix = "ESP";
option optimize_for = CODE_SIZE;
option java_package = "com.spotify.exclusive_mode_esperanto.proto";

message SetEnableRequest {
    bool enable = 1;
}

message GetEnableResponse {
    bool enable = 1;
}

message GetDeviceResponse {
    ResponseCode response = 1;
    DeviceId device_id = 2;
}

message Response {
    ResponseCode response = 1;
}

message DeviceId {
    string id = 1;
    
    oneof _persist {
        bool persist = 2;
    }
}

message Device {
    DeviceId device_id = 1;
    string description = 2;
    string interface = 3;
    bool present = 4;
    bool exclusive = 5;
    string friendly_name = 6;
}

message EnumerateDevicesResponse {
    ResponseCode response = 1;
    repeated Device devices = 2;
}

enum ResponseCode {
    UNKNOWN_ERROR = 0;
    OK = 1;
    NOT_SUPPORTED = 2;
}
