// Extracted from: Spotify 1.2.96.518 (Windows)

syntax = "proto3";

package spotify.timeline_reporter.proto;

option optimize_for = CODE_SIZE;

message ItemReportingContext {
    string content_uri = 1;
    string provider = 7;
    string referrer = 8;
    string decision_id = 9;
    string custom_reporting_attribution = 10;
    string connect_controller_device_id = 11;
    string interaction_id = 17;
    string page_instance_id = 18;
    string play_context = 19;
    
    reserved 2, 3, 4, 5, 6, 12, 13, 14, 15, 16;
}
