// Extracted from: Spotify 1.2.96.518 (Windows)

syntax = "proto3";

package spotify.karaoke_esperanto.proto;

option objc_class_prefix = "ESP";
option java_multiple_files = true;
option optimize_for = CODE_SIZE;
option java_package = "com.spotify.karaoke.esperanto.proto";

message KaraokeSubEventsRequest {
    
}

message KaraokeSubEventsResponse {
    Id id = 1;
    enum Id {
        MASK_READY = 0;
        ERROR = 1;
    }
    
    string track_uri = 2;
    string error_message = 3;
    int32 error_code = 4;
}
