// Extracted from: Spotify 1.2.96.518 (Windows)

syntax = "proto3";

package spotify.list_player.proto;

import "google/protobuf/timestamp.proto";

option optimize_for = CODE_SIZE;

message PlayHistory {
    repeated Item items = 1;
    message Item {
        string uri = 1;
        string list_uri = 2;
        string uid = 3;
        google.protobuf.Timestamp played_at = 4;
        string play_request_id = 6;
        uint64 mft_played_at = 8;
        
        oneof _shuffle_seed {
            string shuffle_seed = 7;
        }
        
        reserved 5;
    }
    
    reserved 2;
}
