// Extracted from: Spotify 1.2.96.518 (Windows)

syntax = "proto3";

package spotify.playback_settings.esperanto.proto;

import "google/protobuf/empty.proto";
import "google/protobuf/wrappers.proto";

option objc_class_prefix = "SPTPlaybackSettingsEsperanto";
option optimize_for = CODE_SIZE;
option java_package = "com.spotify.playback_settings.esperanto.proto";

service PlaybackSettings {
    rpc GetShuffleState(google.protobuf.StringValue) returns (ShuffleState);
    rpc SetShuffleState(SetShuffleStateRequest) returns (google.protobuf.Empty);
    rpc GetSettings(GetSettingsRequest) returns (GetSettingsResponse);
    rpc SetSettings(SetSettingsRequest) returns (google.protobuf.Empty);
    rpc StreamSettingChanges(StreamSettingChangesRequest) returns (stream StreamSettingChange);
    rpc GetDeviceSettings(GetDeviceSettingsRequest) returns (GetDeviceSettingsResponse);
    rpc SetDeviceStreamQuality(SetDeviceStreamQualityRequest) returns (StatusResponse);
    rpc SetMediaMode(SetMediaModeRequest) returns (StatusResponse);
    rpc SetDeviceSettings(SetDeviceSettingsRequest) returns (StatusResponse);
    rpc StreamDeviceSettingFieldChanges(StreamDeviceSettingFieldChangesRequest) returns (stream DeviceSettingFieldChange);
}

message ContentSettings {
    float playback_speed = 3;
    bool shuffle = 4;
    ContextEnhancement context_enhancement = 5;
    
    oneof _skip_finished_episodes {
        bool skip_finished_episodes = 8;
    }
    
    oneof _translation_language {
        string translation_language = 21;
    }
}

message UserSettings {
    oneof _disable_smart_shuffle {
        bool disable_smart_shuffle = 6;
    }
    
    oneof _gapless {
        bool gapless = 9;
    }
    
    oneof _crossfade {
        bool crossfade = 10;
    }
    
    oneof _crossfade_duration_ms {
        int32 crossfade_duration_ms = 11;
    }
    
    oneof _audio_language {
        string audio_language = 22;
    }
    
    oneof _subtitle_language {
        string subtitle_language = 23;
    }
}

message FieldValue {
    oneof value {
        string string_value = 1;
        bool bool_value = 2;
        int32 int_value = 3;
        float float_value = 4;
    }
}

message ShuffleState {
    oneof _shuffle {
        bool shuffle = 1;
    }
    
    oneof _context_enhancement {
        ContextEnhancement context_enhancement = 2;
    }
}

message SetShuffleStateRequest {
    string id = 1;
    bool shuffle_on = 2;
    ContextEnhancement context_enhancement = 3;
}

message SetDisableSmartShuffleRequest {
    bool disable_smart_shuffle = 1;
}

message GetSettingsRequest {
    repeated FieldId requested_setting_fields = 1;
    repeated string content_ids = 2;
    
    oneof _include_user_settings {
        bool include_user_settings = 3;
    }
}

message GetSettingsResponse {
    map<string, ContentSettings> content_settings = 1;
    
    oneof _user_settings {
        UserSettings user_settings = 2;
    }
}

message FieldUpdate {
    FieldId id = 1;
    FieldValue value = 2;
}

message ContentSettingUpdate {
    string content_id = 1;
    repeated FieldUpdate fields = 2;
}

message SetSettingsRequest {
    repeated FieldUpdate user_settings = 1;
    repeated ContentSettingUpdate content_settings = 2;
}

message StreamSettingsRequest {
    repeated FieldId requested_setting_fields = 1;
    repeated string content_ids = 2;
    
    oneof _include_user_settings {
        bool include_user_settings = 3;
    }
}

message StreamSettingsUpdate {
    map<string, ContentSettings> content_settings = 1;
    
    oneof _user_settings {
        UserSettings user_settings = 2;
    }
}

message StreamSettingChangesRequest {
    repeated FieldId requested_setting_fields = 1;
}

message ContentSettingChange {
    string content_id = 1;
    
    oneof field {
        float playback_speed = 3;
        bool shuffle = 4;
        ContextEnhancement context_enhancement = 5;
        bool skip_finished_episodes = 8;
        string translation_language = 21;
    }
}

message UserSettingChange {
    oneof field {
        bool disable_smart_shuffle = 6;
        bool gapless = 9;
        bool crossfade = 10;
        int32 crossfade_duration_ms = 11;
        string audio_language = 22;
        string subtitle_language = 23;
    }
}

message StreamSettingChange {
    oneof change_type {
        ContentSettingChange content_change = 1;
        UserSettingChange user_change = 2;
    }
}

message GetDeviceSettingsRequest {
    string device_id = 1;
}

message GetDeviceSettingsResponse {
    Status status = 1;
    DeviceSettings device_settings = 2;
}

message SetDeviceStreamQualityRequest {
    string device_id = 1;
    int32 quality = 2;
}

message StatusResponse {
    Status status = 1;
}

message DeviceSettings {
    int32 stream_quality = 1;
    
    DeviceCapabilities capabilities = 2;
    message DeviceCapabilities {
        int32 max_supported_stream_quality = 1;
    }
    
    MediaMode media_mode = 7;
    bool normalize = 12;
    int32 normalize_level = 13;
    bool equalizer_enabled = 14;
    float equalizer_low_shelf_gain = 15;
    float equalizer_low_peak_gain = 16;
    float equalizer_low_mid_peak_gain = 17;
    float equalizer_high_mid_peak_gain = 18;
    float equalizer_high_peak_gain = 19;
    float equalizer_high_shelf_gain = 20;
}

message SetMediaModeRequest {
    string device_id = 1;
    MediaMode mode = 2;
}

message SetDeviceSettingsRequest {
    string device_id = 1;
    repeated FieldUpdate fields = 2;
}

message StreamDeviceSettingFieldChangesRequest {
    
}

message DeviceSettingFieldChange {
    string device_id = 1;
    string device_name = 2;
    FieldId field_id = 3;
    FieldValue value = 4;
}

enum Status {
    OK = 0;
    NOT_FOUND = 1;
    INVALID_ARGUMENTS = 2;
    BACKEND_FAILURE = 3;
}

enum FieldId {
    UNKNOWN_FIELD_ID = 0;
    AUDIO_QUALITY = 1;
    SOCIAL_DISCOVERABLE = 2;
    PLAYBACK_SPEED = 3;
    SHUFFLE = 4;
    CONTEXT_ENHANCEMENT = 5;
    DISABLE_SMART_SHUFFLE = 6;
    MEDIA_MODE = 7;
    SKIP_FINISHED_EPISODES = 8;
    GAPLESS = 9;
    CROSSFADE = 10;
    CROSSFADE_DURATION_MS = 11;
    NORMALIZE = 12;
    NORMALIZE_LEVEL = 13;
    EQUALIZER_ENABLED = 14;
    EQUALIZER_LOW_SHELF_GAIN = 15;
    EQUALIZER_LOW_PEAK_GAIN = 16;
    EQUALIZER_LOW_MID_PEAK_GAIN = 17;
    EQUALIZER_HIGH_MID_PEAK_GAIN = 18;
    EQUALIZER_HIGH_PEAK_GAIN = 19;
    EQUALIZER_HIGH_SHELF_GAIN = 20;
    TRANSLATION_LANGUAGE = 21;
    AUDIO_LANGUAGE = 22;
    SUBTITLE_LANGUAGE = 23;
}

enum ContextEnhancement {
    NOT_ENHANCED = 0;
    RECOMMENDATION = 1;
}

enum MediaMode {
    DEFAULT = 0;
    AUDIO = 1;
    VIDEO = 2;
}
