// Extracted from: Spotify 1.2.96.518 (Windows)

syntax = "proto3";

package spotify.playlist4.proto;

option optimize_for = CODE_SIZE;
option java_outer_classname = "PlaylistSyncReasonProto";
option java_package = "com.spotify.playlist4.proto";

message PlaylistSyncReason {
    PlaylistSyncCaller caller = 1;
    bool prioritized = 2;
}

enum PlaylistSyncCaller {
    UNKNOWN = 0;
    ESPERANTO = 1;
    REMOTE = 2;
    ROOTLIST = 3;
    OFFLINE = 4;
    RELOGIN = 5;
    RECENTLY_PLAYED = 6;
    PERMISSIONS = 7;
    PLAYBACK = 8;
    LOCAL_CHANGES = 9;
    TEST = 10;
    FULL_RESET = 11;
    SYNC_POLICY = 12;
    USER_INTERACTION = 13;
    REVERSE_INDEX_BUILDER = 14;
    SIGNAL = 15;
    APPLY_LENSES = 16;
    YOUR_LIBRARY_TAGS = 17;
    PLAYER_CONTEXT_UPDATE = 18;
    CURATION_STATE = 19;
    EPISODE_LIST_LOADER = 20;
    AUDIOBOOK_SEQUENCE_PROVIDER = 21;
    COLLECTION_DECORATE_REQUEST = 22;
    COLLECTION_GET_UNPLAYED_EPISODES_REQUEST = 23;
    COLLECTION_SHOW_OFFLINE_CONTROLLER = 24;
    EPISODE_PUBLISH_DATE_INDEX_WRITE_HOOK = 25;
    PODCAST_PAYWALLS = 26;
    SHOW_ACCESS_SUBSCRIBER = 27;
    SHOW_CONTEXT_LOADER = 28;
    SHOW_COSMOS_DECORATE_REQUEST = 29;
    SHOW_COSMOS_MARK_AS_PLAYED = 30;
    SHOW_COSMOS_SHOW_REQUEST = 31;
    YOUR_LIBRARY_CLEANUP_SUGGESTIONS_HACK = 32;
    YOUR_EPISODES_LOCAL_STATE_UPDATER = 33;
    TAG_PLAYLIST_GENERATOR = 34;
    YOUR_LIBRARY = 35;
    RESUMPTION_PROGRESS = 36;
    SAVED_ALBUMS = 37;
    DSA_STATE_CHANGE = 38;
    SHOW_RESUME_EPISODE_PROVIDER = 39;
    AUTOPLAY_LENS_OBSERVER = 40;
    LIST_PLAYER_DECORATOR = 41;
    LIST_PLAYER_PLAY_REQUEST_ADAPTER = 42;
    PREDEFINED_LISTS = 43;
    JAM_LENS_MANAGER = 44;
    LIST_PLAYER_QUEUED_ITEMS_FILTER = 45;
    LIST_PLAYER_REC_POOL_FILTER = 46;
    VOLATILE_CONTEXT = 47;
    MULTIGET_ADDITIONAL_RESPONSE = 48;
    TRACK_LIST_FACTORY = 49;
    LIST_PLAYER_KEEP_PLAYING_FILTER = 50;
    LIST_CLIENT = 51;
    INTERACTIVE_PLAY_SOURCE = 52;
    LIST_PLAYER_RESOLVED_LIST = 53;
}
