// Extracted from: Spotify 1.2.96.518 (Windows)

syntax = "proto3";

package spotify.recently_played_esperanto.proto;

import "collection/artist_collection_state.proto";
import "collection/album_collection_state.proto";
import "collection/track_collection_state.proto";
import "collection/show_collection_state.proto";
import "collection/episode_collection_state.proto";
import "sync/artist_sync_state.proto";
import "sync/album_sync_state.proto";
import "sync/track_sync_state.proto";
import "sync/episode_sync_state.proto";
import "metadata/artist_metadata.proto";
import "metadata/album_metadata.proto";
import "metadata/track_metadata.proto";
import "metadata/show_metadata.proto";
import "metadata/episode_metadata.proto";
import "played_state/track_played_state.proto";
import "played_state/show_played_state.proto";
import "played_state/episode_played_state.proto";
import "playlist_playlist_state.proto";

option objc_class_prefix = "ESP";
option java_multiple_files = true;
option optimize_for = CODE_SIZE;
option java_package = "com.spotify.recently_played_esperanto.proto";

message RecentlyPlayedArtist {
    cosmos_util.proto.ArtistMetadata artist_metadata = 1;
    cosmos_util.proto.ArtistCollectionState artist_collection_state = 2;
    cosmos_util.proto.ArtistSyncState artist_sync_state = 3;
    uint32 type = 4;
    uint32 add_time = 5;
    string type_str = 6;
}

message RecentlyPlayedAlbum {
    cosmos_util.proto.AlbumMetadata album_metadata = 1;
    cosmos_util.proto.AlbumCollectionState album_collection_state = 2;
    cosmos_util.proto.AlbumSyncState album_sync_state = 3;
    bool in_collection = 4;
    uint32 type = 5;
    uint32 add_time = 6;
    string type_str = 7;
}

message RecentlyPlayedTrack {
    cosmos_util.proto.TrackMetadata track_metadata = 1;
    cosmos_util.proto.TrackCollectionState track_collection_state = 2;
    cosmos_util.proto.TrackPlayState track_play_state = 3;
    cosmos_util.proto.TrackSyncState track_sync_state = 4;
    uint32 type = 5;
    uint32 add_time = 6;
    string type_str = 7;
}

message RecentlyPlayedShow {
    cosmos_util.proto.ShowMetadata show_metadata = 1;
    cosmos_util.proto.ShowCollectionState show_collection_state = 2;
    cosmos_util.proto.ShowPlayState show_play_state = 3;
    uint32 type = 4;
    uint32 add_time = 5;
    string type_str = 6;
}

message RecentlyPlayedEpisode {
    cosmos_util.proto.EpisodeMetadata episode_metadata = 1;
    cosmos_util.proto.EpisodeCollectionState episode_collection_state = 2;
    cosmos_util.proto.EpisodeSyncState episode_offline_state = 3;
    cosmos_util.proto.EpisodePlayState episode_play_state = 4;
    uint32 type = 5;
    uint32 add_time = 6;
    cosmos_util.proto.ShowMetadata show_metadata = 7;
    string type_str = 8;
}

message RecentlyPlayedProfile {
    string link = 1;
    string name = 2;
    string image_uri = 3;
    uint32 offline_state = 4;
    uint32 type = 5;
    uint32 add_time = 6;
    string type_str = 7;
}

message RecentlyPlayedPlaylist {
    playlist.cosmos.proto.PlaylistMetadata playlist_metadata = 1;
    uint32 type = 2;
    uint32 add_time = 3;
    string type_str = 4;
    playlist.cosmos.proto.PlaylistOfflineState offline_state = 5;
}

message RecentlyPlayedCollectionTracks {
    string link = 1;
    uint32 type = 2;
    uint32 add_time = 3;
    string type_str = 4;
}
