// Extracted from: Spotify 1.2.96.518 (Windows)

syntax = "proto2";

package spotify.player.proto;

option optimize_for = CODE_SIZE;

message ModeRestrictions {
    map<string, RestrictionReasons> values = 1;
}

message RestrictionReasons {
    repeated string reasons = 1;
}

message Restrictions {
    repeated string disallow_pausing_reasons = 1;
    repeated string disallow_resuming_reasons = 2;
    repeated string disallow_seeking_reasons = 3;
    repeated string disallow_peeking_prev_reasons = 4;
    repeated string disallow_peeking_next_reasons = 5;
    repeated string disallow_skipping_prev_reasons = 6;
    repeated string disallow_skipping_next_reasons = 7;
    repeated string disallow_toggling_repeat_context_reasons = 8;
    repeated string disallow_toggling_repeat_track_reasons = 9;
    repeated string disallow_toggling_shuffle_reasons = 10;
    repeated string disallow_set_queue_reasons = 11;
    repeated string disallow_interrupting_playback_reasons = 12;
    repeated string disallow_transferring_playback_reasons = 13;
    repeated string disallow_remote_control_reasons = 14;
    repeated string disallow_inserting_into_next_tracks_reasons = 15;
    repeated string disallow_inserting_into_context_tracks_reasons = 16;
    repeated string disallow_reordering_in_next_tracks_reasons = 17;
    repeated string disallow_reordering_in_context_tracks_reasons = 18;
    repeated string disallow_removing_from_next_tracks_reasons = 19;
    repeated string disallow_removing_from_context_tracks_reasons = 20;
    repeated string disallow_updating_context_reasons = 21;
    repeated string disallow_add_to_queue_reasons = 22;
    repeated string disallow_setting_playback_speed = 23;
    map<string, ModeRestrictions> disallow_setting_modes = 25;
    map<string, RestrictionReasons> disallow_signals = 26;
    repeated string disallow_play_as_next_in_queue_reasons = 27;
    repeated string disallow_sleep_timer_clear_reasons = 28;
    repeated string disallow_sleep_timer_duration_reasons = 29;
    repeated string disallow_sleep_timer_end_of_track_reasons = 30;
    repeated string disallow_add_to_queue_track_reasons = 31;
    repeated string disallow_tap_to_play_track_in_next_tracks_reasons = 32;
    repeated string disallow_reordering_track_in_next_tracks_reasons = 33;
    repeated string disallow_reordering_episode_in_next_tracks_reasons = 34;
    repeated string disallow_reordering_enqueued_track_in_next_tracks_reasons = 35;
    repeated string disallow_reordering_enqueued_episode_in_next_tracks_reasons = 36;
    repeated string disallow_viewing_queue_reasons = 37;
    repeated string disallow_viewing_ordered_tracks_in_next_tracks_reasons = 38;
    repeated string disallow_swipe_next_reasons = 39;
    repeated string disallow_swipe_prev_reasons = 40;
    
    reserved 24;
}
