// Extracted from: Spotify 1.2.96.518 (Windows)

syntax = "proto3";

package socialconnect;

option optimize_for = CODE_SIZE;

message Session {
    int64 timestamp = 1;
    string session_id = 2;
    repeated SessionMember session_members = 6;
    bool is_session_owner = 9;
    optional string host_active_device_id = 14; // copied from older proto
    bool active = 17;
    bool redirect_commands = 25;
    
    reserved 8, 12, 22;
    
    reserved "type", "is_discoverable", "quick_blend";
}

message SessionMember {
    string id = 2;
    string username = 3;
    string display_name = 4;
    string image_url = 5;
    bool is_current_user = 10;
}

message SessionUpdate {
    Session session = 1;
    SessionUpdateReason reason = 2;
}

enum SessionUpdateReason {
    UNKNOWN_UPDATE_TYPE = 0;
    NEW_SESSION = 1;
    USER_JOINED = 2;
    USER_LEFT = 3;
    SESSION_DELETED = 4;
    YOU_LEFT = 5;
    YOU_WERE_KICKED = 6;
    YOU_JOINED = 7;
    USER_KICKED = 10;
    VOLUME_CONTROL_PERMISSIONS_CHANGED = 11;
    QUEUE_ONLY_MODE_CONTROL_CHANGED = 12;
    WIFI_BROADCAST_CHANGED = 13;
    ACTIVE_DEVICE_CHANGED = 14;
    SESSION_MEMBER_UPDATED = 16;
    SESSION_ACTIVATED = 17;
}
