// Extracted from: Spotify 1.2.96.518 (Windows)

syntax = "proto3";

package spotify.stream_reporting_esperanto.proto;

import "google/protobuf/timestamp.proto";
import "stream_handle.proto";
import "play_reason.proto";
import "audio_format.proto";

option objc_class_prefix = "ESP";
option optimize_for = CODE_SIZE;
option java_package = "com.spotify.stream_reporting_esperanto.proto";

message StreamEndRequest {
    StreamHandle stream_handle = 1;
    string source_end = 2;
    PlayReason reason_end = 3;
    google.protobuf.Timestamp client_timestamp = 5;
    
    oneof _format {
        AudioFormat format = 4;
    }
}
