// Extracted from: Spotify 1.2.96.518 (Windows)

syntax = "proto3";

package spotify.descriptorextension;

option java_multiple_files = true;
option optimize_for = CODE_SIZE;
option java_package = "com.spotify.descriptorextension.proto";

message ExtensionDescriptor {
    string text = 1;
    float weight = 2;
    repeated ExtensionDescriptorType types = 3;
    string concept_uri = 4;
    string localized_term = 5;
}

message ExtensionDescriptorData {
    repeated ExtensionDescriptor descriptors = 1;
}

enum ExtensionDescriptorType {
    UNKNOWN = 0;
    GENRE = 1;
    MOOD = 2;
    ACTIVITY = 3;
    INSTRUMENT = 4;
    TIME = 5;
    ERA = 6;
    AESTHETIC = 7;
    AUDIENCE = 8;
    CULTURAL_REFERENCE = 9;
    GEOGRAPHIC_LOCATION = 10;
    LANGUAGE = 11;
    LOCATION = 12;
    MEDIA = 13;
    MUSIC_FESTIVAL = 14;
    MUSIC_VENUE = 15;
    MUSICAL_DESCRIPTOR = 16;
    MUSICAL_TERM = 17;
    PLACE = 18;
    PUBLICATION = 19;
    RADIO = 20;
    RECORD_LABEL = 21;
    RECORD_STORE = 22;
    RELIGION = 23;
    SLANG = 24;
}
