// Extracted from: Spotify 1.2.96.518 (Windows)

syntax = "proto3";

package spotify.your_library.proto;

option optimize_for = CODE_SIZE;

message YourLibraryLabelAndImage {
    string label = 1;
    string image = 2;
    bool include_empty = 3;
}

message YourLibraryPredefinedPlaylistConfig {
    InclusionMode inclusion_mode = 1;
    enum InclusionMode {
        EXCLUDE = 0;
        INCLUDE_IF_NOT_EMPTY = 1;
        INCLUDE_ALWAYS = 2;
    }
    
    bool decorate_num_link_types = 2;
}

message YourLibraryPredefinedPlaylistConfigs {
    YourLibraryPredefinedPlaylistConfig liked_songs = 1;
    YourLibraryPredefinedPlaylistConfig your_episodes = 2;
    YourLibraryLabelAndImage new_episodes = 3;
    YourLibraryLabelAndImage local_files = 4;
    YourLibraryPredefinedPlaylistConfig cached_files = 5;
    YourLibraryPredefinedPlaylistConfig highlights = 6;
    YourLibraryPredefinedPlaylistConfig kallax = 7;
    bool all_available_configs_provided = 99;
}

message YourLibraryFilters {
    repeated Filter filter = 1;
    enum Filter {
        ALBUM = 0;
        ARTIST = 1;
        PLAYLIST = 2;
        SHOW = 3;
        BOOK = 4;
        EVENT = 5;
        AUTHOR = 7;
        DOWNLOADED = 100;
        WRITABLE = 101;
        BY_YOU = 102;
        BY_SPOTIFY = 103;
        UNPLAYED = 104;
        IN_PROGRESS = 105;
        FINISHED = 106;
        IS_MIXED = 107;
        UPCOMING = 108;
        VENUE = 109;
        PAST = 110;
        FOLDER = 111;
        PUBLISHED = 112;
        PUBLISHABLE = 113;
        BY_OTHERS = 114;
    }
}

message YourLibrarySortOrder {
    SortOrder sort_order = 1;
    enum SortOrder {
        NAME = 0;
        RECENTLY_ADDED = 1;
        CREATOR = 2;
        CUSTOM = 4;
        RECENTLY_UPDATED = 5;
        RECENTLY_PLAYED_OR_ADDED = 6;
        RELEVANCE = 7;
        EVENT_START_TIME = 8;
        RELEASE_DATE = 9;
        RECENTS = 10;
    }
    
    bool reverse = 2;
}
