// Extracted from: Spotify 1.2.96.518 (Windows)

syntax = "proto3";

package spotify.your_library.proto;

import "your_library_index.proto";
import "collection_index.proto";

option optimize_for = CODE_SIZE;

message YourLibraryEntity {
    oneof entity {
        collection.proto.CollectionAlbumEntry album = 1;
        collection.proto.CollectionArtistEntry artist = 2;
        YourLibraryRootlistEntity rootlist_entity = 3;
        collection.proto.CollectionShowEntry show = 4;
        collection.proto.CollectionBookEntry book = 5;
        YourLibraryPreReleaseEntity prerelease = 7;
        YourLibraryEventEntity event = 8;
        collection.proto.CollectionAuthorEntry author = 9;
        YourLibraryVenueEntity venue = 10;
        YourLibraryConcertCampaignEntity concert_campaign = 11;
    }
}
