// Extracted from: Spotify 1.2.96.518 (Windows)

syntax = "proto3";

package spotify.list.v1.model;

option java_multiple_files = true;
option optimize_for = CODE_SIZE;
option java_outer_classname = "PaginationProto";
option java_package = "com.spotify.list.v1.model";

message Pagination {
    oneof _length {
        int32 length = 1;
    }
    
    oneof _continuation_token {
        bytes continuation_token = 2 [deprecated = true];
    }
    
    oneof _offset {
        int32 offset = 3;
    }
}

message PaginationResponse {
    oneof _next_offset {
        int32 next_offset = 2;
    }
}
